- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    # - import_tasks: tasks/core.yml
    # - import_tasks: tasks/node.yml
    # - import_tasks: tasks/utils.yml
    # - import_tasks: tasks/nvim.yml
    # - import_tasks: tasks/tmux.yml
    # - import_tasks: tasks/stow.yml
    - import_tasks: tasks/rust.yml
    # - import_tasks: tasks/slack.yml
    # - import_tasks: tasks/brave.yml
    # - import_tasks: tasks/insomnia.yml
