- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/node_setup.yml
    - import_tasks: tasks/kitty_setup.yml
    - import_tasks: tasks/nvim_setup.yml
    - import_tasks: tasks/tmux_setup.yml
    - import_tasks: tasks/dot_files.yml

# todo
# install kitty
# install neovim nighly
# move config files into place
