- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: Clippy
  shell: . $HOME/.cargo/env && rustup component add clippy

- name: wasm32-unknown-unknown target
  shell: . $HOME/.cargo/env && rustup target add wasm32-unknown-unknown

- name: aarch64-unknown-linux-gnu target
  shell: . $HOME/.cargo/env && rustup target add aarch64-unknown-linux-gnu

