- name: Install rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  tags:
    - install
    - rust
    - core
- name: Cargo version
  shell: cargo -v
  tags:
    - install
    - rust
    - core
- name: Install clippy
  shell: cargo install clippy
  tags:
    - install
    - rust
    - core
- name: Add wasm32-unknown-unknown target
  shell: rustup target add wasm32-unknown-unknown
  tags:
    - install
    - rust
    - core
- name: Add aarch64-unknown-linux-gnu
  shell: rustup target add aarch64-unknown-linux-gnu
  tags:
    - install
    - rust
    - core
