- name: Installing stow
  become: true
  apt:
    name: stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning cfg
  ansible.builtin.git:
    repo: 'https://github.com/hrryndrsn/cfg.git'
    dest: "{{ lookup('env', 'HOME') }}/cfg"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow nvim
  shell: stow nvim
  args:
    chdir: "{{ lookup('env', 'HOME') }}/cfg"
  tags:
    - install
    - stow
    - nvim
- name: Stow tmux
  shell: stow tmux
  args:
    chdir: "{{ lookup('env', 'HOME') }}/cfg"
  tags:
    - install
    - stow
    - tmux
- name: Stow kitty
  shell: stow kitty
  args:
    chdir: "{{ lookup('env', 'HOME') }}/cfg"
  tags:
    - install
    - stow
    - kitty
